server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: movie_app_api

  # === Spring Boot Mail Configuration ===
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/movie_app_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/movie-app-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

keycloak:
  server-url: http://localhost:${KEYCLOAK_PORT:8080}
  realm: ${KEYCLOAK_REALM:movie-app-realm}
  client-id: ${KEYCLOAK_CLIENT_ID:movie-app-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:NXLH0qSVOgy0eXczjFfDiZrX239D91W5}
  default-role: ROLE_USER

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:movie-assets}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
khqr:
  base-url: ${BAKONG_BASE_URL:https://api-bakong.nbc.gov.kh}
  token: ${BAKONG_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiOTQ3NjEzNTU0YjE0NDkzOCJ9LCJpYXQiOjE3ODk4ODc3MzMsImV4cCI6MTc5NzY2MzczM30.3pY49VJkmGhxlD8iJhmyKxA3L-2pLk3j1LMUqHgMyNI}
  account: ${BAKONG_ACCOUNT_ID:sorn_sophiram@bkrt}
  merchant-name: ${BAKONG_MERCHANT_NAME:SOPHIRAM SORN}
  merchant-city: ${BAKONG_MERCHANT_CITY:Phnom Penh}
  phone: ${BAKONG_PHONE:0969144183}
  store-label: ${BAKONG_STORE_LABEL:KhmerFlixMovie}
  usd-to-khr-rate: ${BAKONG_USD_TO_KHR_RATE:4100}
